// <auto-generated />
using System;
using FoodPal.Providers.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FoodPal.Providers.DataAccess.Migrations
{
    [DbContext(typeof(ProvidersContext))]
    [Migration("20210210211454_seedingDatabase")]
    partial class seedingDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FoodPal.Providers.DomainModel.Catalogue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId")
                        .IsUnique();

                    b.ToTable("Catalogue");
                });

            modelBuilder.Entity("FoodPal.Providers.DomainModel.CatalogueItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CatalogueId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("CatalogueId");

                    b.HasIndex("CategoryId");

                    b.ToTable("CatalogueItems");
                });

            modelBuilder.Entity("FoodPal.Providers.DomainModel.CatalogueItemCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CatalogueItemCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2021, 2, 10, 23, 14, 53, 589, DateTimeKind.Local).AddTicks(9085),
                            Name = "Dessert"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2021, 2, 10, 23, 14, 53, 589, DateTimeKind.Local).AddTicks(9918),
                            Name = "Main Course"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2021, 2, 10, 23, 14, 53, 589, DateTimeKind.Local).AddTicks(9928),
                            Name = "Soups"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2021, 2, 10, 23, 14, 53, 589, DateTimeKind.Local).AddTicks(9932),
                            Name = "Apperitives"
                        });
                });

            modelBuilder.Entity("FoodPal.Providers.DomainModel.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("FoodPal.Providers.DomainModel.ProviderCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProviderCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2021, 2, 10, 23, 14, 53, 583, DateTimeKind.Local).AddTicks(3028),
                            Name = "Mediteranean Cousine"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2021, 2, 10, 23, 14, 53, 587, DateTimeKind.Local).AddTicks(7102),
                            Name = "Tradinional Romanian Cousine"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2021, 2, 10, 23, 14, 53, 587, DateTimeKind.Local).AddTicks(7183),
                            Name = "Japonese Cousine"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2021, 2, 10, 23, 14, 53, 587, DateTimeKind.Local).AddTicks(7190),
                            Name = "Thai Cousine"
                        });
                });

            modelBuilder.Entity("FoodPal.Providers.DomainModel.Catalogue", b =>
                {
                    b.HasOne("FoodPal.Providers.DomainModel.Provider", "Provider")
                        .WithOne("Catalogue")
                        .HasForeignKey("FoodPal.Providers.DomainModel.Catalogue", "ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("FoodPal.Providers.DomainModel.CatalogueItem", b =>
                {
                    b.HasOne("FoodPal.Providers.DomainModel.Catalogue", "Catalogue")
                        .WithMany("Items")
                        .HasForeignKey("CatalogueId");

                    b.HasOne("FoodPal.Providers.DomainModel.CatalogueItemCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalogue");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FoodPal.Providers.DomainModel.Provider", b =>
                {
                    b.HasOne("FoodPal.Providers.DomainModel.ProviderCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FoodPal.Providers.DomainModel.Catalogue", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("FoodPal.Providers.DomainModel.Provider", b =>
                {
                    b.Navigation("Catalogue");
                });
#pragma warning restore 612, 618
        }
    }
}
